on: 
  workflow_dispatch:
  
  push:
    branches:
    - main
    - windows

jobs:
  pyinstaller-build:
    runs-on: [windows-latest, macOS-latest]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10.6'
          spec: 'Sound and Lighting.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Sound and Lighting'
          options: ''
